### ISSUE TITLE
About us/location/map

### ISSUE THREAD

**Issue by Klumpish** [Klumpish/kino-bio-projekt#40]
This card is connected to #36 

As a user
I want to be able to find a map that shows me here the cinema is located
So that i can find my way there.

**Acceptance Criteria**

- a map that shows the location of the cinema

Tasks
 

- [x] create a map image
- [x] add the map
- [x] add small discription
- [x] style the text and image so that they are next to each other

 How it should look

![Image](https://github.com/user-attachments/assets/71594c46-ebd4-4517-88d4-415dc022a6f2)

**Is this tested?**
 

- [ ] Yes

**Comment by Dusknery** [comment]
s:t Olofsgatan 10
753 12 Uppsala
